---
- name: Setup Apache on webservers with specific tags
  hosts: localhost

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
      tags: apache_install

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
      tags: apache_service