[azure_vms]
client-1 ansible_host=172.191.46.201
client-2 ansible_host=172.174.102.243

[azure_vms:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/azure_ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_connection=ssh
