---
- name: Copy file from local to remote and change its permissions
  hosts: all
  become: yes
  tasks:
    - name: Copying file
      become: true
      copy:
        src: /mnt/c/users/FabianGuerreroMontañ/Documents/Github/udemy-courses/ansible/Apuntes.txt
        dest: /tmp/Apuntes.txt
        owner: azureuser
        group: azureuser
        mode: '0644'
    - name: Changing file permissions
      file: 
        path: /tmp/Apuntes.txt
        owner: azureuser
        group: azureuser
        mode: '0755'
        state: file