---
- name: Schedule a cronjob on remote hosts
  hosts: all
  tasks:
    - name: Schedule cron
      cron:
        name: "Daily Backup Job"
        minute: "0"
        hour: "10"
        day: "*"
        month: "*"
        weekday: "4"
        user: root
        job: "/home/my-scripts/cfile.sh"